export const lessons = [
  { title: "Find the claim", explanation: "A claim is something the writer asks you to accept. Separate the main conclusion from the reasons offered for it.", example: "‘Students using flashcards scored higher, so flashcards improve learning.’ The conclusion is that flashcards improve learning; the score difference is the offered evidence.", question: "‘The program ran faster after caching was added. We should use caching everywhere.’ What is the main conclusion?", options: ["The program ran faster", "We should use caching everywhere", "Caching always reduces memory use"], correct: 1, feedback: "‘We should use caching everywhere’ is the recommendation the writer wants you to accept. A faster run is supporting evidence, but does not justify using caching in every situation." },
  { title: "Inspect the evidence", explanation: "Ask what was observed, how it was measured, and whether it actually supports the claim. A statement can be evidence without being conclusive proof.", example: "One successful test shows that the program worked for that input. It does not establish that it works for every input.", question: "A model gets 95% accuracy on its training examples. What does this directly establish?", options: ["It will achieve 95% on new data", "It performed well on those training examples", "It has no bias"], correct: 1, feedback: "The measurement describes the training examples. Performance on unseen data requires a separate evaluation." },
  { title: "Expose assumptions", explanation: "An assumption is an unstated idea needed to connect evidence to a conclusion. Ask: what must be true for this argument to work?", example: "‘This library was fastest in my benchmark, so it will be fastest in our app’ assumes the benchmark represents the app’s workload.", question: "‘This code is correct because it passed the tests.’ Which assumption needs scrutiny?", options: ["The tests cover the relevant requirements and edge cases", "The code uses short variable names", "Every program has the same requirements"], correct: 0, feedback: "Passing tests supports correctness only for what those tests meaningfully check. Missing cases or incorrect expected results weaken that conclusion." },
  { title: "Check the inference", explanation: "An inference moves from information to a conclusion. Ask whether the conclusion must follow, is merely plausible, or is unsupported. Distinguish a necessary condition from a sufficient one.", example: "‘All valid records have an ID. This record has an ID.’ An ID alone does not prove validity; other requirements may also apply.", question: "All correctly paired datasets use matching image and label indices. This dataset uses matching indices. Must its labels be correct?", options: ["Yes, matching indices guarantee correct original labels", "No, the original labels might already be wrong", "No dataset can have correct labels"], correct: 1, feedback: "Shared indices preserve existing pairings. They do not repair originally incorrect labels. Preservation of alignment and accuracy of labels are different claims." },
  { title: "Consider alternatives", explanation: "Ask what else could explain the observation. Correlation and a before/after change do not, by themselves, establish causation. Look for comparisons that separate competing explanations.", example: "If accuracy improves after changing both the model and the dataset, either change—or their interaction—could explain it.", question: "Students who use a study app score higher. What alternative explanation should you investigate?", options: ["They may already study more or have different prior knowledge", "The app definitely caused the difference", "Scores cannot be measured"], correct: 0, feedback: "Motivation, study time, or prior knowledge could differ between groups. A fair comparison helps distinguish these from the app’s effect." },
  { title: "Conclude with the right confidence", explanation: "State what the evidence supports, what remains uncertain, and what would change your mind. A counterexample can refute an ‘always’ claim; one positive example cannot prove it.", example: "‘This optimization helped on the tested workload; we need broader benchmarks before generalizing’ keeps the conclusion within the evidence.", question: "A function passes three ordinary inputs but has not been tested on empty input. Which conclusion is justified?", options: ["It is correct for all inputs", "It passed those three cases; empty-input behavior remains untested", "It is definitely incorrect"], correct: 1, feedback: "Neither universal correctness nor definite failure follows. Report the successful cases and the remaining uncertainty." },
];

export const steps = [
  { key: "claim", title: "What is the main claim?", hint: "Restate the conclusion in your own words. If this is descriptive text with no argument, say so and identify the main point." },
  { key: "evidence", title: "What evidence is actually given?", hint: "Quote a short phrase or identify a result. Distinguish the author's statements from independently verified facts. Say if evidence is missing." },
  { key: "assumptions", title: "What is being assumed?", hint: "What must be true for the evidence to support the conclusion? Identify unstated conditions or missing context." },
  { key: "inference", title: "Does the conclusion follow?", hint: "Explain the link between evidence and claim. Is it necessary, plausible, or unsupported? For code, trace a small example." },
  { key: "alternatives", title: "What else could explain it?", hint: "Give an alternative explanation, boundary case, or counterexample. What comparison or test would distinguish the possibilities?" },
  { key: "conclusion", title: "What can you reasonably conclude?", hint: "Write a qualified conclusion. State your uncertainty and what new evidence would change your mind." },
] as const;

export const sample = "A class started using a flashcard app and its average exam score rose from 65 to 78. The teacher concludes that the app caused the improvement and recommends it to every class. The report does not describe changes in study time, exam difficulty, or the students taking each exam.";
export const workedExample = [
  "The teacher claims the app caused the improvement and should be used by every class.",
  "The reported average increased from 65 to 78. The paragraph gives no comparison group or details about how comparable the exams were.",
  "The argument assumes the groups and exams are comparable, other relevant conditions did not change, and other classes would benefit similarly.",
  "The timing is consistent with an app benefit, but a before/after comparison alone does not isolate its effect.",
  "More study time, an easier exam, or different students could explain the change. Compare similar groups on comparable assessments while accounting for those factors.",
  "Scores improved after the app was introduced, but the cause is uncertain. More controlled evidence is needed before attributing the improvement to the app or recommending it universally.",
];
